language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls
  - pip install -r requirements
script:
  coverage run --source=saltshaker sh tests/runtests.sh
after_success:
  coveralls
